# Generated by Django 2.0.3 on 2018-03-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file2',
            name='secondfile',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
